apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: 637423430820.dkr.ecr.us-east-1.amazonaws.com/microfirst:latest/microfirst
      context: ../../microfirst
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
